//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACS.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceBooking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServiceBooking()
        {
            this.SelectedServices = new HashSet<SelectedService>();
        }
    
        public int Id { get; set; }
        public System.DateTime BookingDate { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public double TotalAmmount { get; set; }
        public string Status { get; set; }
        public string PickupAddress { get; set; }
        public string DropAddress { get; set; }
        public string Feedback { get; set; }
        public int VehicleId { get; set; }
        public int DealerId { get; set; }
    
        public virtual Dealer Dealer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SelectedService> SelectedServices { get; set; }
    }
}
